name: ding
on:
  schedule:
  - cron: '0 10 1 * *'  #每月第1号18:00  #每12小时 "0 0/12 * * *"
  workflow_dispatch:
jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send ding

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: sender
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run ding
      run: |
        python ./ding.py ${{ secrets.DD_TOKEN }}
    #- run: pip install requests && python ./ding.py ${{ secrets.DD_TOKEN }}

    env:
      DD_TOKEN: ${{ secrets.DD_TOKEN }}
