name: run

on:
  schedule:
    - cron: "0 0/12 * * *"  #每12小时
jobs:
  build:
    runs-on: ubuntu-latest
    name: send_dd
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run dd
      run: |
        python ./run.py ${{ secrets.DD_TOKEN }}
