name: zhiban
on:
  schedule:
  - cron:   '50 9 * * *' #40 3,9=每日11点40,17点40，两个时间点执行任务
  workflow_dispatch:
jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send zhiban to your friend

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'
        architecture: 'x64'
    - run: pip install datetime json requests && python ./zhiban.py

    env:
      TOKEN_DD: ${{ secrets.TOKEN_DD }}
      MOBIE: ${{ secrets.MOBIE }}
