name: zhiban
on:
  schedule:
    - cron: '50 9 * * *' #40 3,9=每日11点40,17点40，两个时间点执行任务
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-python@v4 # 使用python装配器
        with:
          python-version: '3.9' # 指定python版本
          cache: 'poetry' # 设置缓存
      - run: pip3 install datetime json requests
      - run: poetry install --without dev # 安装
      - run: poetry run python .\zhiban.py # 执行
