name: zhiban
on:
  schedule:
  - cron:   '40 9 * * *' #'40 9 1 * *'=每月1号17点40, #'40 3,9 * * *'=每日两个时间点11点40,17点40 执行任务
  workflow_dispatch:
jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send zhiban to your friend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.x'
        architecture: 'x64'
    - run: pip install requests && python ./zhiban.py

    env:
      TOKEN_DD: ${{ secrets.TOKEN_DD }}
      MOBIE: ${{ secrets.MOBIE }}
